### ISSUE TITLE
feature request: url-select customization for new protocols

### ISSUE THREAD

**Issue by eschulte** [muennich/urxvt-perls#34]
Currently the protocols are hard coded in https://github.com/muennich/urxvt-perls/blob/master/url-select#L64, it would be nice if new protocols could be added from .xdefaluts/.xresources.

Cheers,

**Comment by blueyed** [comment]
Thanks @eschulte - I'm coming from a search.. :)

I found some issues with this:

It would be nice, if the default could be kept/used, e.g. if not only "pattern.0" would trigger the custom patterns, and "pattern.0" would be assigned the default value then.
Especially since it's non-trivial to use the default due to necessary escaping (space between '//' to not consider it as being comments, escaping of '\').
Using quotes did not help here, because they were used in the pattern then literally?!

My use case is adding an additional pattern for git ranges.

I'm using the following now:

    URxvt.matcher.pattern.0: (?:https?:/ /|ftp:/ /|news:/ /|mailto:|file:/ /|\\bwww\\.) [\\w\\-\\@;\\/?:&=%\\$.+!*\\x27,~#]* ( \\([\\w\\-\\@;\\/?:&=%\\$.+!*\\x27,~#]*\\) | [\\w\\-\\@;\\/?:&=%\\$+*~])+
    URxvt.matcher.pattern.1: [a-f0-9]{7,}\.\.[a-f0-9]{7,}
