### ISSUE TITLE
Multiline urls

### ISSUE THREAD

**Issue by pmaziere** [muennich/urxvt-perls#6]
When a url spans accross several lines in the terminal, only the first line part is selected.
It should select the whole url rather than the truncated part

**Comment by archenemies** [comment]
Solution: download the following file into ~/.urxvt/ext/url-select: http://ofb.net/~frederik/urxvt/url-select.new (if you trust me)

Here is a diff so you can see what I changed: http://ofb.net/~frederik/urxvt/url-select.patch

Ultimately the fix was pretty easy. The Urxvt perl code is pretty well designed, and fun to work with. It's somewhat annoying that the Urxvt maintainers don't want to fix the behavior of lines in curses-based applications, but I guess some of my lines occupy exactly 79 columns and if I had a URL which ended at column 79 then the above patch would mistakenly merge it with the next line. (or whatever $COLUMNS is for you)

**Comment by tblancher** [comment]
@archenemies Your patch doesn't work for me, and it kills url-select.  No error, it seems syntactically correct, but my keysym doesn't launch the selector anymore.

**Comment by archenemies** [comment]
Nothing on urxvt STDERR?

**Comment by tblancher** [comment]
Nope, it's just empty.  Nothing to suggest a problem.

**Comment by archenemies** [comment]
Hrm. Did you check that the code in ~/.urxvt/ext/url-select is
actually being executed? For instance by inserting a "warn" statement?

I don't know what else to suggest. The version I provided worked fine
for me... Do you have a custom pattern configured?

**Comment by tblancher** [comment]
Actually, I found some old code for matcher that I had been using that does
multiline URLs properly (and allows me to click on them, more natural for me
than url-select).

I'll post it when I have time.

**Comment by tblancher** [comment]
I finally decided to switch back to rxvt-unicode after terminology does not yet have a way to define the terminfo file it uses.  Part of that switch to get urxvt functional was to get the old matcher code I'd been using working again.  This anti-bitrot, or whatever you want to call it, just works now:

[matcher.txt](https://github.com/muennich/urxvt-perls/files/181178/matcher.txt)

That's a Perl file, copyright of its respective authors.  It has multiline detection code which appears to be absent in the officially distributed matcher file.  This makes multiline URLs completely clickable in mutt+elinks.  This was the reason why went away from urxvt in the first place, the multiline URLs had been broken.

**Comment by potuz** [comment]
I had been using the matcher file posted by @tblancher until my last update in which it stopped working. It highlights multiple line urls but it no longer launches them on clicks. I reverted back to the matcher in rxvt-unicode-9.22 and now I can launch url but not multiple lines.
